// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzV8hkkWYba2Z_S9FVhdto1k3hbfudlw',
    appId: '1:125095256640:web:0c11e497302e50c0f4b5a5',
    messagingSenderId: '125095256640',
    projectId: 'eternal-seeker-333707',
    authDomain: 'eternal-seeker-333707.firebaseapp.com',
    storageBucket: 'eternal-seeker-333707.appspot.com',
    measurementId: 'G-MK6YL1P99H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-cemxAosO-S_0i4eXBqYoWciKMh61pA',
    appId: '1:125095256640:android:8c9b06fce4d89b68f4b5a5',
    messagingSenderId: '125095256640',
    projectId: 'eternal-seeker-333707',
    storageBucket: 'eternal-seeker-333707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQvsnC5TljgZ4Aszm681zQDlDusP2OkM',
    appId: '1:125095256640:ios:afb65e9c0bdfe315f4b5a5',
    messagingSenderId: '125095256640',
    projectId: 'eternal-seeker-333707',
    storageBucket: 'eternal-seeker-333707.appspot.com',
    iosClientId: '125095256640-dn6a9n5mbljfcsln5eo1run3r6p05fds.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwQvsnC5TljgZ4Aszm681zQDlDusP2OkM',
    appId: '1:125095256640:ios:d39a6b05afba1ce1f4b5a5',
    messagingSenderId: '125095256640',
    projectId: 'eternal-seeker-333707',
    storageBucket: 'eternal-seeker-333707.appspot.com',
    iosClientId: '125095256640-kbtf11vikh74ol713nv5jnhn4nel6e7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookin.RunnerTests',
  );
}
